# Build stage
FROM node:22-alpine AS builder
WORKDIR /app

# Install deps
COPY package.json package-lock.json ./
RUN npm ci --silent

# Copy sources
COPY . .

# Accept build-time API url (defaults to HTTPS localhost services)
ARG VITE_API_URL="https://localhost:3000"
ARG VITE_GAMEY_URL="https://localhost:4000"

ENV VITE_API_URL=$VITE_API_URL
ENV VITE_GAMEY_URL=$VITE_GAMEY_URL

RUN npm run build

# Production image
FROM nginx:stable-alpine
# configuración personalizada de Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
